AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys a Module specific IAM permissions

Parameters:
  DeploymentName:
    Type: String
    Description: The name of the deployment
  ModuleName:
    Type: String
    Description: The name of the Module
  RoleName:
    Type: String
    Description: The name of the IAM Role

Resources:
  Policy:
    Type: AWS::IAM::Policy
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W12
            reason: The actions with "*" are all ones that only support the all resources wildcard
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:ListStacks # W11 exception
              - cloudformation:ValidateTemplate # W11 exception
            Resource: "*"
          - Effect: Allow
            Action:
              - cloudformation:CreateChangeSet
              - cloudformation:CreateStack
              - cloudformation:DeleteChangeSet
              - cloudformation:DeleteStack
              - cloudformation:DescribeChangeSet
              - cloudformation:DescribeStackEvents
              - cloudformation:ExecuteChangeSet
              - cloudformation:SetStackPolicy
              - cloudformation:UpdateStack
              - cloudformation:GetTemplateSummary
            Resource:
              - !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/sdlf-cfn-module-*
          - Effect: Allow
            Action:
              - cloudformation:DescribeStacks
            Resource:
              - !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/sdlf-cfn-module-*
          - Effect: Allow
            Action:
              - cloudformation:RegisterType
              - cloudformation:SetTypeDefaultVersion
              - cloudformation:DescribeType
              - cloudformation:DeregisterType
            Resource:
              - !Sub "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/MODULE/awslabs::sdlf::*"
              - !Sub "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/module/awslabs-sdlf-*"
              - !Sub "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/MODULE/*"
              - !Sub "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/module/*"
          - Effect: Allow
            Action:
              - cloudformation:DescribeTypeRegistration # W11 exception
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
              - ssm:PutParameter
              - ssm:AddTagsToResource
              - ssm:ListTagsForResource
              - ssm:RemoveTagsFromResource
              - ssm:DeleteParameter
            Resource:
              - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/SDLF/CFN/*
          - Effect: Allow
            Action:
              - codeartifact:PublishPackageVersion
              - codeartifact:DeletePackageVersions
            Resource:
              - !Sub arn:${AWS::Partition}:codeartifact:${AWS::Region}:${AWS::AccountId}:package/*/*/pypi/*
        Version: "2012-10-17"
      PolicyName: !Sub sdlf-${DeploymentName}-${ModuleName}
      Roles: [!Ref RoleName]
