AWSTemplateFormatVersion: 2010-09-09
Description: iot team datasets

Parameters:
    pPipelineReference:
        Type: String
        Default: none

Resources:
    rLegislators:
        Type: awslabs::sdlf::dataset::MODULE
        Properties:
            pPipelineReference: !Ref pPipelineReference
            pTeamName: iot
            pDatasetName: legislators
