AWSTemplateFormatVersion: "2010-09-09"
Description: iot team pipelines

Parameters:
    pPipelineReference:
        Type: String
        Default: none

Resources:
    rMain:
        Type: AWS::CloudFormation::Stack
        DeletionPolicy: Delete
        UpdateReplacePolicy: Delete
        Properties:
            TemplateURL: ./pipeline-main.yaml
            Parameters:
                pPipelineReference: !Ref pPipelineReference
            Tags:
                - Key: sdlf:pipeline
                  Value: main
    rSingleStage:
        Type: AWS::CloudFormation::Stack
        DeletionPolicy: Delete
        UpdateReplacePolicy: Delete
        Properties:
            TemplateURL: ./pipeline-singlestage.yaml
            Parameters:
                pPipelineReference: !Ref pPipelineReference
            Tags:
                - Key: sdlf:pipeline
                  Value: singlestage
