AWSTemplateFormatVersion: "2010-09-09"
Description: Main pipeline

Parameters:
    pPipelineReference:
        Type: String
        Default: none

Resources:
    rMainA:
        Type: awslabs::sdlf::stageA::MODULE
        Properties:
            pPipelineReference: !Ref pPipelineReference
            pStageName: A
            pPipeline: main
            pTeamName: iot
            pTriggerType: event
            pEventPattern: >-
                {
                    "source": ["aws.s3"],
                    "detail-type": ["Object Created"],
                    "detail": {
                        "bucket": {
                            "name": ["{{resolve:ssm:/SDLF/S3/RawBucket}}"]
                        },
                        "object": {
                            "key": [{ "prefix": "iot/legislators/" }]
                        }
                    }
                }
            pEnableTracing: false

    rMainB:
        Type: awslabs::sdlf::stageB::MODULE
        Properties:
            pPipelineReference: !Ref pPipelineReference
            pDatasetBucket: "{{resolve:ssm:/SDLF/S3/StageBucket}}"
            pStageName: B
            pPipeline: main
            pTeamName: iot
            pTriggerType: schedule
            pEventPattern: !Sub >-
                {
                    "source": ["aws.states"],
                    "detail-type": ["Step Functions Execution Status Change"],
                    "detail": {
                        "status": ["SUCCEEDED"],
                        "stateMachineArn": ["arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:sdlf-iot-main-sm-A"]
                    }
                }
            pSchedule: "cron(*/5 * * * ? *)"
            pEnableTracing: false
