AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::LanguageExtensions
Description: Deploy Glue jobs

Parameters:
  pArtifactsBucket:
    Description: The artifacts bucket used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/S3/ArtifactsBucket
  pTeamName:
    Description: Name of the team (all lowercase, no symbols or spaces)
    Type: String
  pGlueJobs:
    Description: List of glue job names
    Type: CommaDelimitedList
    AllowedPattern: "^[a-zA-Z0-9\\-]*$"
  pEnableVpc:
    Description: Deploy SDLF resources in a VPC
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/VPC/Enabled

Conditions:
  GlueJobsNotEmpty: !Not
    - !Equals
      - !Join ["", !Ref pGlueJobs]
      - ""
  RunInVpc: !Equals [!Ref pEnableVpc, true]

Resources:
  rGlueRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /service-role/
      PermissionsBoundary: !Sub "{{resolve:ssm:/SDLF/IAM/${pTeamName}/TeamPermissionsBoundary}}"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSGlueServiceRole
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonS3FullAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: !Sub sdlf-${pTeamName}-glue-job
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kms:CreateGrant
                  - kms:Decrypt
                  - kms:DescribeKey
                  - kms:Encrypt
                  - kms:GenerateDataKey*
                  - kms:ReEncrypt*
                Resource:
                  - !Sub "{{resolve:ssm:/SDLF/KMS/${pTeamName}/InfraKeyId}}"
                  - !Sub "{{resolve:ssm:/SDLF/KMS/${pTeamName}/DataKeyId}}"
                  - "{{resolve:ssm:/SDLF/KMS/KeyArn}}"

  "Fn::ForEach::GlueJobResources":
  - GlueJobName
  - !Ref pGlueJobs
  - "r&{GlueJobName}GlueJob":
      Type: AWS::Glue::Job
      Condition: GlueJobsNotEmpty
      Properties:
        Command:
          Name: glueetl
          PythonVersion: "3"
          ScriptLocation: !Sub s3://${pArtifactsBucket}/${pTeamName}/transforms/${GlueJobName}.py
        DefaultArguments: !If
          - RunInVpc
          -
            "--job-bookmark-option": job-bookmark-disable
            "--enable-glue-datacatalog": "true"
            "--enable-continuous-cloudwatch-log": "true"
            "--enable-continuous-log-filter": "true"
            "--enable-metrics": "true"
            "--disable-proxy-v2": "true"
          -
            "--job-bookmark-option": job-bookmark-disable
            "--enable-glue-datacatalog": "true"
            "--enable-continuous-cloudwatch-log": "true"
            "--enable-continuous-log-filter": "true"
            "--enable-metrics": "true"
        ExecutionProperty:
          MaxConcurrentRuns: 10
        MaxRetries: 0
        MaxCapacity: 2.0
        GlueVersion: "4.0"
        Name: !Sub
          - sdlf-${pTeamName}-${BaseGlueJobName}
          - BaseGlueJobName: !Select [0, !Split ["-", !Ref GlueJobName]]
        SecurityConfiguration: !Sub "{{resolve:ssm:/SDLF/Glue/${pTeamName}/SecurityConfigurationId}}"
        Role: !Ref rGlueRole
        Connections: !If
          - RunInVpc
          - Connections:
              - BUILDSTEPVARIABLE_GLUECONNECTIONS
          - !Ref "AWS::NoValue"
