AWSTemplateFormatVersion: "2010-09-09"
Description: CICD resources to handle deployment of a new team (repository)

Parameters:
  pKMSKey:
    Description: The KMS key used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/KMS/CICDKeyId
  pDomain:
    Description: Name of the data domain (all lowercase, no symbols or spaces)
    Type: String
    AllowedPattern: "[a-z0-9]{2,9}"
  pTeamName:
    Description: Team name
    Type: String
  pGitPlatform:
    Description: Platform used to host git repositories
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/Misc/GitPlatform
  pMainRepositoriesPrefix:
    Type: String
    Default: sdlf-main-

Conditions:
  GitPlatformCodeCommit: !Equals [!Ref pGitPlatform, "CodeCommit"]
  GitPlatformGitLab: !Equals [!Ref pGitPlatform, "GitLab"]
  GitPlatformGitHub: !Equals [!Ref pGitPlatform, "GitHub"]

Resources:
  rTeamMainCodeCommit:
    Type: AWS::CodeCommit::Repository
    Condition: GitPlatformCodeCommit
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
    Properties:
      Code:
        BranchName: main
        S3: ./README.md
      RepositoryDescription: !Sub ${pDomain} ${pTeamName} main repository
      RepositoryName: !Sub ${pMainRepositoriesPrefix}${pDomain}-${pTeamName}
      KmsKeyId: !Ref pKMSKey

  rTeamMainGitLab:
    Type: GitLab::Projects::Project
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Condition: GitPlatformGitLab
    Properties:
      Name: !Sub ${pMainRepositoriesPrefix}${pDomain}-${pTeamName}
#      Path: "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"

  rTeamMainGitHub:
    Type: GitHub::Repositories::Repository
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
    Condition: GitPlatformGitHub
    Properties:
      Org: !Sub "{{resolve:ssm:/SDLF/${pGitPlatform}/Group}}"
      Name: !Sub ${pMainRepositoriesPrefix}${pDomain}-${pTeamName}
      Private: true
      Visibility: private
      Archived: false

  rTeamMainCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /SDLF/${pGitPlatform}/${pTeamName}/Main${pGitPlatform}
      Type: String
      Value: !If
        - GitPlatformCodeCommit
        - !GetAtt rTeamMainCodeCommit.Name
        - !Sub ${pMainRepositoriesPrefix}${pDomain}-${pTeamName} # !GetAtt rTeamMainGitLab.Name
      Description: !Sub Name of the ${pDomain} ${pTeamName} main repository
