name: Performance Testing
# on:
#  schedule:
#    - cron: '*/5 * * * *'
#  push:
#    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Generate timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

    - name: Install Lighthouse
      run: |
        npm install -g lighthouse puppeteer

    - name: Create reports directory
      run: mkdir -p ./lighthouse-reports

    # Updated file paths in Lighthouse command
    - name: Run Lighthouse
      run: |
        lighthouse https://www.test.diegoph.people.aws.dev \
          --chrome-flags="--headless --no-sandbox --disable-gpu" \
          --output html --output json \
          --output-path ./lighthouse-reports/report

    # Debug step to verify files
    - name: List generated files
      run: |
        echo "Contents of lighthouse-reports directory:"
        ls -la ./lighthouse-reports/

    # Updated file paths in upload step
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lighthouse-report-${{ steps.timestamp.outputs.timestamp }}
        path: |
          ./lighthouse-reports/report.report.html
          ./lighthouse-reports/report.report.json
        retention-days: 7

    # Updated file paths in verification step
    - name: Check for results
      if: always()
      run: |
        if [ -f "./lighthouse-reports/report.report.html" ] && [ -f "./lighthouse-reports/report.report.json" ]; then
          echo "Reports generated successfully"
        else
          echo "Warning: Some reports are missing"
          exit 1
        fi
