name: Performance Testing
on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Generate timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

    - name: Install Lighthouse
      run: |
        npm install -g lighthouse puppeteer

    - name: Run Lighthouse
      run: |
        lighthouse https://www.test.diegoph.people.aws.dev \
          --chrome-flags="--headless --no-sandbox --disable-gpu" \
          --output html --output json \
          --output-path ./lighthouse-report

    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lighthouse-report-${{ steps.timestamp.outputs.timestamp }}
        path: |
          ./lighthouse-report.html
          ./lighthouse-report.json
        retention-days: 7

    - name: Log completion
      if: always()
      run: |
        echo "Test completed at $(date)"
        ls -la ./
