name: Performance Testing
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    # Updated checkout action to v4
    - uses: actions/checkout@v4
    
    # Add timestamp for logging
    - name: Get timestamp
      id: timestamp
      run: echo "time=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

    # Run Lighthouse
    - name: Lighthouse Check
      uses: treosh/lighthouse-ci-action@v10
      with:
        urls: |
          https://www.test.diegoph.people.aws.dev
        uploadArtifacts: true
        temporaryPublicStorage: true

    # Updated upload-artifact to v4
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lighthouse-results-${{ steps.timestamp.outputs.time }}
        path: .lighthouseci
        retention-days: 7
