name: Performance Testing
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Add timestamp for logging
    - name: Get timestamp
      id: timestamp
      run: echo "::set-output name=time::$(date +'%Y-%m-%d %H:%M:%S')"

    # Run Lighthouse
    - name: Lighthouse Check
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://yourwebsite.com'
        outputDirectory: ./lighthouse-results
        
    # Optional: Save results to artifact
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: lighthouse-results-${{ steps.timestamp.outputs.time }}
        path: ./lighthouse-results

    # Optional: Add error handling
    - name: Check for failures
      if: ${{ failure() }}
      run: |
        echo "Test failed at ${{ steps.timestamp.outputs.time }}"
        # Add notification logic here
